#if !defined(AFX_POLYCTL_H__AF149361_39BE_11D1_9304_00600820B4FF__INCLUDED_)
#define AFX_POLYCTL_H__AF149361_39BE_11D1_9304_00600820B4FF__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPolyCtl wrapper class

class CPolyCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPolyCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
		= { 0x4CBBC676, 0x507F, 0x11D0, { 0xB9, 0x8B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetFillColor(unsigned long newValue);
	unsigned long GetFillColor();
	short GetSides();
	void SetSides(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POLYCTL_H__AF149361_39BE_11D1_9304_00600820B4FF__INCLUDED_)
