Attribute VB_Name = "GlobalVariables"
'THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
'ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
'THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
'PARTICULAR PURPOSE.

'Copyright  2000  Microsoft Corporation.  All Rights Reserved

Option Explicit

Public Declare Sub Sleep Lib "Coredll" (ByVal dwMilliseconds As Long)

Public GuessLevel As Integer        'Level of play
Public ComputerString As String     'String to hold the random colors generated by the computer
Public UserString As String         'String to hold the user input
Public FileMenu As MenuBarMenu
Public GameMenu As MenuBarMenu
Public HelpMenu As MenuBarMenu


