//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
//
// Use of this sample source code is subject to the terms of the Microsoft
// license agreement under which you licensed this sample source code. If
// you did not accept the terms of the license agreement, you are not
// authorized to use this sample source code. For the terms of the license,
// please see the license agreement between you and Microsoft or, if applicable,
// see the LICENSE.RTF on your install media or the root of your tools installation.
// THE SAMPLE SOURCE CODE IS PROVIDED "AS IS", WITH NO WARRANTIES OR INDEMNITIES.
//
//------------------------------------------------------------------
// <autogenerated>
// This code was generated by Visual Studio 2005.
// Changes to this file may cause incorrect behavior and 
// will be lost if the code is regenerated.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Use of this source code is subject to the terms of your Windows Mobile
// Software Shared Source Premium Derivatives License Form or other
// applicable Microsoft license agreement for the software. If you did not
// accept the terms of such a license, you are not authorized to use this
// source code.
//
// </autogenerated>
//------------------------------------------------------------------

namespace Microsoft.WindowsMobile.Samples.RingToneManager
{
    partial class FrmManager
    {
        private System.Windows.Forms.ProgressBar progressBar1;
        private System.Windows.Forms.MenuItem mnuScan;
        private System.Windows.Forms.MenuItem mnuMenu;
        private System.Windows.Forms.MenuItem mnuExit;
        private System.Windows.Forms.MenuItem mnuPreview;
        private System.Windows.Forms.MainMenu mainMenu2;
        private System.Windows.Forms.MenuItem mnuStop;
        private System.Windows.Forms.MenuItem mnuAddRingTone;
        private System.Windows.Forms.ListView lvwSoundFiles;
        private System.Windows.Forms.ColumnHeader chFileName;
        private System.Windows.Forms.ColumnHeader chDirectory;

        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.MainMenu mainMenu1;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
               this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", MessageId = "System.Windows.Forms.Control.set_Text(System.String)"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", MessageId = "System.Windows.Forms.ColumnHeader.set_Text(System.String)"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:DoNotPassLiteralsAsLocalizedParameters", MessageId = "System.Windows.Forms.MenuItem.set_Text(System.String)")]
        private void InitializeComponent()
        {
            this.mainMenu1 = new System.Windows.Forms.MainMenu();
            this.mnuScan = new System.Windows.Forms.MenuItem();
            this.mnuMenu = new System.Windows.Forms.MenuItem();
            this.mnuPreview = new System.Windows.Forms.MenuItem();
            this.mnuStop = new System.Windows.Forms.MenuItem();
            this.mnuAddRingTone = new System.Windows.Forms.MenuItem();
            this.mnuExit = new System.Windows.Forms.MenuItem();
            this.progressBar1 = new System.Windows.Forms.ProgressBar();
            this.mainMenu2 = new System.Windows.Forms.MainMenu();
            this.lvwSoundFiles = new System.Windows.Forms.ListView();
            this.chFileName = new System.Windows.Forms.ColumnHeader();
            this.chDirectory = new System.Windows.Forms.ColumnHeader();
            this.SuspendLayout();
            // 
            // mainMenu1
            // 
            this.mainMenu1.MenuItems.Add(this.mnuScan);
            this.mainMenu1.MenuItems.Add(this.mnuMenu);
            // 
            // mnuScan
            // 
            this.mnuScan.Text = "Scan Device";
            this.mnuScan.Click += new System.EventHandler(this.MnuScan_Click);
            // 
            // mnuMenu
            // 
            this.mnuMenu.MenuItems.Add(this.mnuPreview);
            this.mnuMenu.MenuItems.Add(this.mnuStop);
            this.mnuMenu.MenuItems.Add(this.mnuAddRingTone);
            this.mnuMenu.MenuItems.Add(this.mnuExit);
            this.mnuMenu.Text = "Menu";
            // 
            // mnuPreview
            // 
            this.mnuPreview.Text = "Preview Sound";
            this.mnuPreview.Click += new System.EventHandler(this.MnuPreview_Click);
            // 
            // mnuStop
            // 
            this.mnuStop.Text = "Stop all Sounds";
            this.mnuStop.Click += new System.EventHandler(this.MnuStop_Click);
            // 
            // mnuAddRingTone
            // 
            this.mnuAddRingTone.Text = "Add to ring tones";
            this.mnuAddRingTone.Click += new System.EventHandler(this.MnuAddRingTone_Click);
            // 
            // mnuExit
            // 
            this.mnuExit.Text = "Exit";
            this.mnuExit.Click += new System.EventHandler(this.MnuExit_Click);
            // 
            // progressBar1
            // 
            this.progressBar1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.progressBar1.Location = new System.Drawing.Point(3, 3);
            this.progressBar1.Name = "progressBar1";
            this.progressBar1.Size = new System.Drawing.Size(234, 21);
            // 
            // lvwSoundFiles
            // 
            this.lvwSoundFiles.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.lvwSoundFiles.Columns.Add(this.chFileName);
            this.lvwSoundFiles.Columns.Add(this.chDirectory);
            this.lvwSoundFiles.Location = new System.Drawing.Point(3, 30);
            this.lvwSoundFiles.Name = "lvwSoundFiles";
            this.lvwSoundFiles.Size = new System.Drawing.Size(234, 235);
            this.lvwSoundFiles.TabIndex = 7;
            this.lvwSoundFiles.View = System.Windows.Forms.View.Details;
            
            // 
            // chFileName
            // 
            this.chFileName.Text = "File name";
            this.chFileName.Width = 164;
            // 
            // chDirectory
            // 
            this.chDirectory.Text = "Path";
            this.chDirectory.Width = 400;
            // 
            // FrmManager
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(240, 268);
            this.Controls.Add(this.lvwSoundFiles);
            this.Controls.Add(this.progressBar1);
            this.KeyPreview = true;
            this.Menu = this.mainMenu1;
            this.Name = "FrmManager";
            this.Text = "Ring Tone Manager";
            this.ResumeLayout(false);
        }
        #endregion
    }
}

