[CEAppManager]
Version = 1.0
Component = Blackjack

[Blackjack]
Description = Sample AppInstall application
; Uninstall = Black Jack
; Do not specify the "InstallDir" key so that CEAppMgr will use the directory of this INI file
; as the install directory.
IconFile = blkjack.ico
IconIndex = 0
DeviceFile = Blackjack.exe
CabFiles = blkjack.ppc201_sh3.cab,blkjack.ppc201_mips.cab,blkjack.ppc211_sh3.cab,blkjack.ppc211_mips.cab,blkjack.ppc30_sh3.cab,blkjack.ppc30_mips.cab,
;CabFiles = blkjack.ppc211_sh3.cab,blkjack.ppc211_mips.cab,blkjack.ppc30_sh3.cab,blkjack.ppc30_mips.cab,
