<%

bodyXML = bodyXML + "  &lt;characteristic type=&quot;CM_Planner&quot; &gt;" + vbcrlf
bodyXML = bodyXML + "    &lt;characteristic type=&quot;PreferredConnections&quot; /&gt;" + vbcrlf
bodyXML = bodyXML + "      &lt;parm name=&quot;{F28D1F74-72BE-4394-A4A7-4E296219390C}&quot; value=&quot;PPP1&quot; /&gt;" + vbcrlf
bodyXML = bodyXML + "      &lt;parm name=&quot;{7022E968-5A97-4051-BC1C-C578E2FBA5D9}&quot; value=&quot;PPP2&quot; /&gt;" + vbcrlf
bodyXML = bodyXML + "      &lt;parm name=&quot;{A1182988-0D73-439e-87AD-2A5B369F808B}&quot; value=&quot;PPP3&quot; /&gt;" + vbcrlf
bodyXML = bodyXML + "      &lt;parm name=&quot;{436EF144-B4FB-4863-A041-8F905A62C572}&quot; value=&quot;PPP4&quot; /&gt;" + vbcrlf
bodyXML = bodyXML + "    &lt;/characteristic&gt;" + vbcrlf
bodyXML = bodyXML + "    &lt;parm name=&quot;FailoverPrompt&quot; value=&quot;1&quot;/&gt;" + vbcrlf
bodyXML = bodyXML + "    &lt;parm name=&quot;FailoverRetry&quot; value=&quot;3&quot;/&gt;" + vbcrlf
bodyXML = bodyXML + "    &lt;parm name=&quot;CacheTime&quot; value=&quot;120&quot;/&gt;" + vbcrlf
bodyXML = bodyXML + "    &lt;parm name=&quot;RetryCount&quot; value=&quot;3&quot;/&gt;" + vbcrlf
bodyXML = bodyXML + "  &lt;/characteristic&gt;" + vbcrlf


%>
