; This is the database initialization file.
; format is as follows -
; Database : <db name> : <type in hex> : <num sort order> : <hex propid> : <hex flags> ....
;    CEDB_SORT_DESCENDING         0x00000001
;    CEDB_SORT_CASEINSENSITIVE    0x00000002
;    CEDB_SORT_UNKNOWNFIRST       0x00000004
;    CEDB_SORT_GENERICORDER       0x00000008
; A database specifier can be followed by any number of record specifiers
; Record : 
; A record specifier can be followed by any number of field specifiers
; Field : <hex propid> : <value> [ either string or hex dword ]
; End   (ends a matching database or a record context)

Database: "DB_notify_events" : 0 : 1 : 0001001F : 0
; 0001001F - PROPIDR_NAME
; 0002001F - PROPIDR_CMDLINE
; 00030013 - PROPIDR_EVENT
Record :
Field : 0001001F : "repllog.exe"
Field : 0002001F : "AppRunAtRs232Detect"
Field : 00030013 : 9
End
Record :
Field : 0001001F : "clocknot.exe"
Field : 0002001F : "AppRunAfterRestore"
Field : 00030013 : A
End
Record :
Field : 0001001F : "clocknot.exe"
Field : 0002001F : "AppRunAfterTimeChange"
Field : 00030013 : 1
End
Record :
Field : 0001001F : "calnot.exe"
Field : 0002001F : "AppRunAfterRestore"
Field : 00030013 : A
End
Record :
Field : 0001001F : "calnot.exe"
Field : 0002001F : "AppRunAfterTimeChange"
Field : 00030013 : 1
End
End Database

Database: "\\DesktopPositions" : 42424242 : 2 : 42010003 :0 : 4204001F : 0
End Database 
Database: "Appointments Database" : 19 : 3 : 420d0040 : 0 : 42230002 : 0 : 42130003 : 0
End Database 
Database: "Tasks Database" : 1A : 3 : 0037001F : 2 : 410F0002 : 0 : 00260003 : 0
End Database 

Database: "Contacts Database" : 18 : 2 : 4013001f : 2 : 3A06001F : 2
End Database


; NOTE: This list must be kept in sync with the file \private\cmnapps\shared\pimutil\pimutil.rc
; 0x4001001f = HHPR_CATNAME
; 0x40020002 = HHPR_CATBITNUM
; 0x40030002 = HHPR_CATFLAGS
; 0x40040002 = HHPR_CATCOUNT_ADDR
; 0x40050002 = HHPR_CATCOUNT_CAL
; 0x40060002 = HHPR_CATCOUNT_TASK
Database: "\\Categories Database" : 1B : 3 : 4001001f : 2 : 40020002 : 2 : 40030002 : 2
Record :
Field : 4001001f : "Business"
Field : 40020002 : 0
Field : 40030002 : 1
Field : 40040002 : 0
Field : 40050002 : 0
Field : 40060002 : 0
End
Record :
Field : 4001001f : "Personal"
Field : 40020002 : C
Field : 40030002 : 1
Field : 40040002 : 0
Field : 40050002 : 0
Field : 40060002 : 0
End

End Database



