// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "sketch.h"

/////////////////////////////////////////////////////////////////////////////
// CSketcCtl

IMPLEMENT_DYNCREATE(CSketcCtl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSketcCtl properties

/////////////////////////////////////////////////////////////////////////////
// CSketcCtl operations

void CSketcCtl::Erase()
{
  InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL, NULL);
}


short CSketcCtl::get_PenWidth()
{
	short result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CSketcCtl::put_PenWidth(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}
