#if !defined(AFX_SKETCHCTL_H__AF149361_39BE_11D1_9304_00600820B4FF__INCLUDED_)
#define AFX_SKETCHCTL_H__AF149361_39BE_11D1_9304_00600820B4FF__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSketcCtl wrapper class

class CSketcCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSketcCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
		= { 0xCBF9C2BE, 0xE8CB, 0x11D0, { 0xAF, 0xAE, 0x00, 0x60, 0x08, 0x11, 0xD2, 0xB6 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:

	void Erase();
	short get_PenWidth();
	void put_PenWidth(short);

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SKETCHCTL_H__AF149361_39BE_11D1_9304_00600820B4FF__INCLUDED_)
