/////////////////////////////////////////////////////////////////////////////
// Copyright (c) Microsoft Corporation.  All rights reserved.
/////////////////////////////////////////////////////////////////////////////

#pragma once

#define DISPID_BEFORENAVIGATE2          100
#define DISPID_COMMANDSTATECHANGE       101
#define DISPID_DOCUMENTCOMPLETE         102
#define DISPID_DOWNLOADBEGIN            103
#define DISPID_DOWNLOADCOMPLETE         104
#define DISPID_NAVIGATECOMPLETE2        105
#define DISPID_NEWWINDOW2               106
#define DISPID_ONFULLSCREEN             107
#define DISPID_ONMENUBAR                108
#define DISPID_ONQUIT                   109
#define DISPID_ONSTATUSBAR              110
#define DISPID_ONTHEATERMODE            111
#define DISPID_ONTOOLBAR                112
#define DISPID_ONVISIBLE                113
#define DISPID_ONPROGRESSCHANGE         114
#define DISPID_PROPERTYCHANGE           115
#define DISPID_STATUSTEXTCHANGE         116
#define DISPID_TITLECHANGE              117
    // _DPIEWebBrowserEvents2 now supported by Browser

#define DISPID_BEFORENAVIGATE           140
#define DISPID_NAVIGATECOMPLETE         141
#define DISPID_NEWWINDOW                142
    // NOTE: These are old DISPID only used for File Browser/CFolder

#define DISPID_BROWSERNAVIGATE          150
#define DISPID_BROWSERREFRESH           151
#define DISPID_BROWSERSTOP              152
#define DISPID_BROWSERBUSY              153
#define DISPID_BROWSERTITLE             154
#define DISPID_BROWSERLOCATION          155
#define DISPID_BROWSERISFRAME           156
#define DISPID_BROWSERSCROLLSTYLE       157
#define DISPID_BROWSERMARGINWIDTH       158
#define DISPID_BROWSERMARGINHEIGHT      159
#define DISPID_BROWSERFRAMENAVIGATE     160
#define DISPID_BROWSERSELECTEDCODEPAGE  161
#define DISPID_BROWSERPOINTER           162
#define DISPID_BROWSERDOCUMENT          163
#define DISPID_BROWSERSCRIPT            164
#define DISPID_BROWSERFOCUSRECTENABLED  165

#define DISPID_BROWSERLAYOUTWIDTH       175
#define DISPID_BROWSERLAYOUTHEIGHT      176
#define DISPID_BROWSERLOCATIONBASEURL   177
#define DISPID_BROWSERCLEARTYPEENABLED  178
#define DISPID_BROWSERSCRIPTINGENABLED  179
#define DISPID_BROWSERFITTOWINDOW       180
#define DISPID_BROWSERSHOWIMAGES        181
#define DISPID_BROWSERPLAYSOUNDS        182
#define DISPID_BROWSERZOOMLEVEL         183
#define DISPID_BROWSERINTEGRALPAGING    184
#define DISPID_BROWSERCONTEXTMENU       185
#define DISPID_BROWSERACTIVEXENABLED    186
#define DISPID_BROWSERSELECTIONENABLED  187
#define DISPID_BROWSERCANCOPY           188

#define DISPID_FRAMEBEFORENAVIGATE      200
#define DISPID_FRAMENAVIGATECOMPLETE    201
#define DISPID_FRAMENEWWINDOW           204

#define DISPID_ONHISTORYLIMITCHANGE     262   // send when the history limit has been updated or the 'clear history' button has been pressed.

#define DISPID_HTMLWINDOWEVENTS_ONLOAD              0x0100
#define DISPID_HTMLWINDOWEVENTS_ONUNLOAD            0x0101

#define DISPID_HTMLFRAMESETEVENTS_ONLOAD            0x0116
#define DISPID_HTMLFRAMESETEVENTS_ONUNLOAD          0x0117

#define DISPID_HTMLANCHORELEMENTEVENTS_ONCLICK      0x0130

#define DISPID_HTMLFORMELEMENTEVENTS_ONSUBMIT       0x0140
#define DISPID_HTMLFORMELEMENTEVENTS_ONRESET        0x0141

#define DISPID_HTMLINPUTELEMENTEVENTS_ONCLICK       0x0151
#define DISPID_HTMLINPUTELEMENTEVENTS_ONFOCUS       0x0152
#define DISPID_HTMLINPUTELEMENTEVENTS_ONBLUR        0x0153
#define DISPID_HTMLINPUTTEXTELEMENTEVENTS_ONCHANGE  0x0154

#define DISPID_HTMLSELECTELEMENTEVENTS_ONCHANGE     0x0160
#define DISPID_HTMLSELECTELEMENTEVENTS_ONFOCUS      0x0161
#define DISPID_HTMLSELECTELEMENTEVENTS_ONBLUR       0x0162

#define DISPID_HTMLTEXTAREAELEMENTEVENTS_ONCHANGE   0x0170
#define DISPID_HTMLTEXTAREAELEMENTEVENTS_ONFOCUS    0x0171
#define DISPID_HTMLTEXTAREAELEMENTEVENTS_ONBLUR     0x0172

#define DISPID_HTMLDOCUMENT_BASE                    0x1000
#define DISPID_HTMLWINDOW_BASE                      0x1100
#define DISPID_HTMLFRAMEELEMENT_BASE                0x1200
#define DISPID_HTML_SCREEN_BASE                     0x1300
