#ifndef __SMILECTL_H__
#define __SMILECTL_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSmileCtl wrapper class

class CSmileCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSmileCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc01fa303, 0xb475, 0x11d1, { 0x87, 0xe8, 0x0, 0x60, 0x97, 0xba, 0x8d, 0x75 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetBorderStyle();
	void SetBorderStyle(short);
	LPFONTDISP GetFont();
	void SetFont(LPFONTDISP);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	BSTR GetCaption();
	void SetCaption(LPCTSTR);
	BOOL GetSad();
	void SetSad(BOOL);

// Operations
public:
	void Beep();
	void Wink(BOOL bWink);
	void AboutBox();
};

#endif // __SMILECTL_H__
