// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "counter.h"

/////////////////////////////////////////////////////////////////////////////
// CFullCtrl1

IMPLEMENT_DYNCREATE(CCounter, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCounter properties

/////////////////////////////////////////////////////////////////////////////
// CCounter operations
void CCounter::StartCounting()
{
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCounter::SetMaxCounter(int nMax)
{
	static BYTE parms[] = {VT_I4};
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms, nMax);
}

void CCounter::GetInfoFromCounter(LPCTSTR pInfo)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms, pInfo);
}
