#if !defined(AFX_COUNTER_H__30533701_41C6_11D1_9307_00600820B4FF__INCLUDED_)
#define AFX_COUNTER_H__30533701_41C6_11D1_9307_00600820B4FF__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCounter wrapper class

class CCounter : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCounter)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x30533701, 0x41C6, 0x11d1, { 0x93, 0x7, 0x0, 0x60, 0x8, 0x20, 0xb4, 0xff } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void StartCounting();
	void SetMaxCounter(int nMax);
	void GetInfoFromCounter(LPCTSTR pInfo);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COUNTER_H__30533701_41C6_11D1_9307_00600820B4FF__INCLUDED_)
