#ifndef __MATHSCTL_H__
#define __MATHSCTL_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMathsCtl wrapper class

class CMathsCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMathsCtl)
public:
	CLSID const& GetClsid()
	{
 		static CLSID const clsid1
			= { 0x183cb003, 0xbeed, 0x11ce, { 0x96, 0x11, 0, 0xaa, 0, 0x4a, 0x75, 0xcf } };
		static CLSID const clsid2
			= { 0x181CB003, 0xbeed, 0x11ce, { 0x96, 0x11, 0x0, 0xaa, 0x0, 0x4a, 0x75, 0xcf } };
		static CLSID const clsid3
			= { 0x182cb003, 0xbeed, 0x11ce, { 0x96, 0x11, 0x0, 0xaa, 0x0, 0x4a, 0x75, 0xcf } };
		if (m_idControl == 0)
			return clsid1;
		else if (m_idControl == 1)
			return clsid2;
		return clsid3;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	BOOL GetOpposite();
	void SetOpposite(BOOL);

// Operations
public:
	int m_idControl;
	void AboutBox();
};

#endif // __MATHSCTL_H__
